### PR TITLE
Total revamp of readline support.

### PR DESCRIPTION
**Pull request by clementfarabet**
Now using plain C bindings to readline, instead of this super messy ffi+coroutine binding.

The completion system is now in C, taken from the one we have in LuaJIT.

The line parsing, history, multiline support, support for "no =", is still implemented in Lua.

Notes/TODO:
* multiline works, but pasting code results in double prints (not sure how to fix that)
* there's no readline.so detection, it just assumes the lib exists (we should add cmake detection, anyone interested?)

This new version seems to fix problems reported in [this issue](https://github.com/torch/trepl/issues/11).

### CODE REVIEW

**Comment by clementfarabet** [comment]
Yeah I think it can be merged, it can only be better than the current
version :-)

**Comment by soumith** [comment]
ok let me compile on my machine once, and merge. thanks for this awesome cleanup.

**Comment by soumith** [comment]
ok tested that it builds out of the box (and runs fine) on OSX and Ubuntu 14.04. merging!

**Comment by soumith** [comment]
there's no more linenoise etc right, the README should be corrected accordingly?

**Comment by clementfarabet** [comment]
Great, let me know if you find any bug with this version. I have one patch
coming for an edge case when compiling =.

**Pull request merged**
